FROM node:20-alpine AS base
RUN npm i -g pnpm

FROM base AS builder
WORKDIR /app
COPY package.json .
RUN pnpm i
COPY . .
RUN pnpm build
RUN pnpm prune --prod

FROM base AS runner
WORKDIR /app
COPY --from=builder /app/build build/
COPY --from=builder /app/node_modules node_modules/
COPY package.json .
EXPOSE 3000
EXPOSE 5174
CMD node build



